# Generated by Django 5.2.8 on 2025-11-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title_healine2',
        ),
        migrations.AddField(
            model_name='about',
            name='title_headline2',
            field=models.CharField(db_default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_headline1',
            field=models.CharField(db_default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_headline3',
            field=models.CharField(db_default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.CharField(db_default='', max_length=100),
        ),
    ]
