# Generated by Django 5.2.8 on 2025-11-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0003_remove_about_title_healine2_about_title_headline2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title_headline2',
        ),
        migrations.AddField(
            model_name='about',
            name='title_healine2',
            field=models.CharField(db_default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_headline1',
            field=models.CharField(db_default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_headline3',
            field=models.CharField(db_default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.CharField(db_default='', max_length=200),
        ),
    ]
