# Generated by Django 5.2.8 on 2025-11-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0004_remove_about_title_headline2_about_title_healine2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.CharField(db_default='', max_length=100),
        ),
    ]
