# Generated by Django 5.2.8 on 2025-11-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0005_alter_about_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title_headline1',
            field=models.CharField(db_default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_headline3',
            field=models.CharField(db_default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_healine2',
            field=models.CharField(db_default='', max_length=100),
        ),
    ]
