# Generated by Django 5.2.8 on 2025-11-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0006_alter_about_title_headline1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_service', models.CharField(db_default='', max_length=100)),
                ('title', models.CharField(db_default='', max_length=100)),
                ('description', models.TextField(db_default='', max_length=300)),
                ('speed', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
