# Generated by Django 5.2.8 on 2025-11-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0007_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_default='', max_length=100)),
                ('title', models.CharField(db_default='', max_length=200)),
                ('short_description', models.TextField(default='', max_length=500)),
                ('client', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
                ('description', models.TextField(db_default='', max_length=1000)),
                ('image', models.ImageField(upload_to='image_portfolio')),
            ],
        ),
    ]
